/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  purge: {
    safelist: [
      'border-connected',
      'text-connected',
      'bg-connected',
      'bg-function-light',
      'bg-function-dark',
      'bg-product-light',
      'bg-product-dark',
      'bg-location-light',
      'bg-location-dark',
      'bg-installed-light',
      'bg-installed-dark',
      'bg-noAspect-light',
      'bg-noAspect-dark',
      'bg-unspecifiedAspect-light',
      'bg-unspecifiedAspect-dark',
      'text-function-foreground-light',
      'text-function-foreground-dark',
      'text-product-foreground-light',
      'text-product-foreground-dark',
      'text-location-foreground-light',
      'text-location-foreground-dark',
      'text-installed-foreground-light',
      'text-installed-foreground-dark',
      'text-noAspect-foreground-light',
      'text-noAspect-foreground-dark',
      'text-unspecifiedAspect-foreground-light',
      'text-unspecifiedAspect-foreground-dark',
    ],
  },
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        consolas: ['Consolas', 'Monaco', 'monospace'],
      },
      colors: {
        'navbar-dark': '#232528',
        block: '#ff5f5f',
        connector: '#5f5fff',
        terminal: '#5fff5f',
        fulfilled: '#fcd34c',
        connected: '#bfdbfe',
        part: '#4ade80',
        transfer: '#60a5fa',
        'function-light': '#ffff00',
        'product-light': '#00ffff',
        'location-light': '#ff00ff',
        'installed-light': '#424bb2',
        'noAspect-light': '#ffffff',
        'unspecifiedAspect-light': '#cccccc',
        'function-dark': '#ffff00',
        'product-dark': '#00ffff',
        'location-dark': '#ff00ff',
        'installed-dark': '#424bb2',
        'noAspect-dark': '#ffffff',
        'unspecifiedAspect-dark': '#cccccc',
        'function-foreground-light': '#000000',
        'product-foreground-light': '#000000',
        'location-foreground-light': '#000000',
        'installed-foreground-light': '#ffffff',
        'noAspect-foreground-light': '#000000',
        'unspecifiedAspect-foreground-light': '#000000',
        'function-foreground-dark': '#000000',
        'product-foreground-dark': '#000000',
        'location-foreground-dark': '#000000',
        'installed-foreground-dark': '#ffffff',
        'noAspect-foreground-dark': '#000000',
        'unspecifiedAspect-foreground-dark': '#000000',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
